Otra
EtherealPain/hello-world pull request #10
Opened 2020-01-06 14:51 UTC by santelys

2020-01-06 15:00 UTC, EtherealPain reviewed
parametrizable publico

2020-01-06 15:00 UTC, EtherealPain commented on ejemplo.txt
> +
..

2020-01-06 15:00 UTC, EtherealPain commented on ejemplo2.txt
> +l;,;l,;l,
q

2020-01-06 16:45 UTC, santelys reviewed
me parece bien pero soy yo jajaja

2020-01-07 14:57 UTC, EtherealPain commented on ejemplo.txt
>      Ut euismod enim eu dui rutrum consectetur sit amet nec metus.
No creo que sea correcto este lorem

2020-01-07 15:00 UTC, EtherealPain commented on ejemplo2.txt
> +Si yo estoy claro de lo que te asusta
no

2020-01-07 15:01 UTC, EtherealPain commented on ejemplo2.txt
> +Aguanta Lucero...
lucero

2020-01-07 18:50 UTC, santelys reviewed
finish touye review

2020-01-07 18:50 UTC, santelys commented on ejemplo.txt
>      Ut euismod enim eu dui rutrum consectetur sit amet nec metus.
cierto

2020-01-07 18:50 UTC, santelys commented on ejemplo.txt
> +
claro

2020-01-07 18:52 UTC, EtherealPain submitted a review, later dismissed

2020-01-07 18:56 UTC, adha-luna submitted a review, later dismissed

2020-01-07 20:01 UTC, EtherealPain approved these changes

2020-01-07 20:03 UTC, adha-luna requested changes
no me gusta

2020-01-07 20:03 UTC, adha-luna approved these changes

2020-01-07 20:11 UTC, EtherealPain reviewed
Esto es un comentario editado

2020-01-08 12:39 UTC, merged